### ISSUE TITLE
clarify license of `cdo-bindings`

### ISSUE THREAD

**Issue by larsbuntemeyer** [Try2Code/cdo-bindings#49]
It's not clear to me which license is invoked with `cdo-bindings`. The conda feedstock says:

https://github.com/conda-forge/python-cdo-feedstock/blob/d8dcf0fa49b178185272c33e6d074df2211f2603/recipe/meta.yaml#L38

```yaml
about:
  home: https://code.zmaw.de/projects/cdo/wiki/Cdo%7Brbpy%7D
  license: GPL-2.0-or-later
  license_file: COPYING
  summary: Use CDO in the context of Python as if it would be a native library
```

while in the README:

https://github.com/Try2Code/cdo-bindings/blob/master/README.md#license

> Cdo.{rb,py} makes use of the BSD-3-clause license

GPL is copyleft while BSD not, so that makes quite a difference.
